[package]
name = "nabe"
version = "0.1.0"
authors = ["Adrián Bielsa <63594921+adrianbielsa1@users.noreply.github.com>"]
edition = "2018"

[[bin]]
name = "nabe"
path = "source-code/binary.rs"

[lib]
name = "nabe"
path = "source-code/library.rs"
